## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.0
  - 1.2
  - 1.3

os:
  - linux
  - osx

notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("IMFData")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("IMFData")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
